### ISSUE TITLE
Can't get script to work

### ISSUE THREAD

**Issue by shmeetz** [mike-edel/ID-MultiPageImporter#18]
I have tried on 2 computers, in 2019 and 2021 versions. I have placed the script in the program files scripts location as well as in the users scripts location as recommended in a previous comment. It asks me for the pdf, I select it and then it has that blue circle twirling infinitely... any suggestions?

**Comment by mike-edel** [comment]
@shmeetz 
I would generally recommend to only use the user scripts folder for installing scripts. 
Program files will most likely cause issues (at least on Windows systems) since it will not allow the standard operating system user to write to that folder. That means the script won't be able do write to it as well and it tries to save the config into the script folder. 
Try removing the one in program files first and only install it into the user scripts folder like described here: 
https://creativepro.com/how-to-install-scripts-in-indesign/

If that doesn't help: can you please share some more details? 
- Operating system and version
- exact InDesign version (Help->about)
- can you manually place the same pdf into the same InDesign file without issues?
- can you create a test pdf from InDesign using one of the standard pdf presets and try that one?
- are either the document or the pdf unusual in terms of dimensions (very small, very large)?

**Comment by shmeetz** [comment]
Thank you so much for taking time to respond.
I placed the script in the following folder:C:\Users\EEMA\AppData\Roaming\Adobe\InDesign\Version 14.0
AND same for Version 16.0 because I have both installed on my computer.
I removed the script from the program file folder. Now it's just in the user folder. I checked your link to make sure I put it in the right place.
All of that was done before I posted and script wouldn't run in either 19 or 20 ID
Operating System: Windows 10 Version 2004 (OS Build 19041.985)ID version 16.1 x64 and version 14.1.2 x64Yes I can manually place the same pdf into the same file without issuesWhen I create a test pdf from indesign, that one DOES work The document is not unusual dimensions... it's half US letter

So your trouble shooting recommendations are telling me that there's something wrong with my pdf. My pdf was created by exporting to pdf from google slides. I guess I will have to play around with saving that in a different way in order to make it work then! Thank you thank you! Now I know what the problem is at least!
Smile  

    On Wednesday, June 2, 2021, 04:19:23 PM CDT, Mike ***@***.***> wrote:  
 
 


@shmeetz
I would generally recommend to only use the user scripts folder for installing scripts.
Program files will most likely cause issues (at least on Windows systems) since it will not allow the standard operating system user to write to that folder. That means the script won't be able do write to it as well and it tries to save the config into the script folder.
Try removing the one in program files first and only install it into the user scripts folder like described here:
https://creativepro.com/how-to-install-scripts-in-indesign/

If that doesn't help: can you please share some more details?
   
   - Operating system and version
   - exact InDesign version (Help->about)
   - can you manually place the same pdf into the same InDesign file without issues?
   - can you create a test pdf from InDesign using one of the standard pdf presets and try that one?
   - are either the document or the pdf unusual in terms of dimensions (very small, very large)?

**Comment by mike-edel** [comment]
Caused by the input pdf file
