### ISSUE TITLE
Indesign 2021 Bug

### ISSUE THREAD

**Issue by SkylarAstarot** [mike-edel/ID-MultiPageImporter#23]
I am trying to transcribe a book, but when using the import script it freezes at 83% i use Adobe Indesign 2021 v16.3.
Fix this please and check the spelling.

**Comment by mike-edel** [comment]
Hi, 

I just tested the last script version (2.6.4) again on the latest CC2021 version (16.4.1 running on Windows) with no problems.
Can you provide more details on your environment:
Windows or Mac
Full InDesign and Script version

Have you tried manually placing the document (PDF?) in question to verify that it works?
In my experience, in many cases such issues are caused by the document you try to place.

Can you also please be more specific regarding the spelling issues? 

Cheers,
Mike

**Comment by SkylarAstarot** [comment]
Hello Mike, I tried to carry out the procedure in a 52-page catalog with images and I had no problems, I think it was blocked due to the size, the error that I describe is for a 671-page PDF Book.

Environment:
Windows 10 Enterprise 21H2 - 19044.1466
Adobe Indesign 2021 v16.3
MultiPageImporter 2.6.2 - It is the version downloaded directly from this repository

Line 760 ...."Rotatation:" Do you mean rotation?

**Comment by mike-edel** [comment]
Ah, okay.
One thing that helped in the past was to lower the Indesign display quality for embedded content before starting. High quality display often consumes too much system memory.

On Jan 15, 2022, 13:39, at 13:39, "Skylär Astaröt" ***@***.***> wrote:
>Hello Mike, I tried to carry out the procedure in a 52-page catalog
>with images and I had no problems, I think it was blocked due to the
>size, the error that I describe is for a 671-page PDF Book.
>
>Environment:
>Windows 10 Enterprise 21H2 - 19044.1466
>Adobe Indesign 2021 v16.3
>MultiPageImporter 2.6.2 - It is the version downloaded directly from
>this repository
>
>Line 760 ...."Rotatation:" Do you mean rotation?
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/mike-edel/ID-MultiPageImporter/issues/23#issuecomment-1013675455
>You are receiving this because you were assigned.
>
>Message ID:
***@***.***>
