### ISSUE TITLE
MultiPageImporter error 11265

### ISSUE THREAD

**Issue by HEDONIST474** [mike-edel/ID-MultiPageImporter#6]
Firstly thanks for this great script!
Few days ago I bought a new PC, installed latest version of InDesign and tryed to import multipage PDF into my project but had a problemm: there is a error of Script when I am trying to set scale value less than 33%. It is very strange because on previous PC i had no such a problems. I tryed different PDF`s and the same. 

![2019-06-25_10-09-57](https://user-images.githubusercontent.com/52193091/60076965-8873e880-9731-11e9-92c6-ca19e3911cfe.png)

Can you help?

**Comment by mike-edel** [comment]
Hi,
were you using the latest version of the script? 
Which version of InDesign are you using? (latest is 14.02) - I assume on Windows?

I have come across this error before and so far it always was a case where the inserted object would really end up outside the pasteboard (area around the actual page). 
I remember that this sometimes was caused by one of these things:
- unusual default units in the target document
- very large object that's inserted
- small pasteboard area

You can test the following: in InDesign's preferences there is a setting how large the pasteboard area is. Try increasing this quite a bit. 
![id_pasteboard](https://user-images.githubusercontent.com/22517839/60113584-5cc52280-9772-11e9-90e0-8b081fd694e7.png)

Note: if you change this setting when no document is opened it will become the new default for all documents. From the error I would assume that the vertical size is the issue.

If that doesn't help it would be great if you could share a sample with me:
- source document
- target document
- settings you use when inserting

Cheers,
Mike

**Comment by HEDONIST474** [comment]
Hi!
Thanks fo reply! Actualy increasing "Vertical marging" settings helped but it is very strange because on my previous PC with exactly the same settings your script works with no problemm. 
A little bit later I'll get all infomaion in one place and send you as a case, maybe it will help to preserve same problems in future!
